In [1]:
# Programmgeruest zu Versuch 1, Aufgabe 4)
import numpy as np
import pandas as pd
from time import clock
from random import randint
from V1A2_Classifier import *


In [2]:
# (I) Load data 
forestdata  = pd.read_csv('./Foresttypesdata.csv'); # load data as pandas data frame 
classlabels = ['s','h','d','o'];                                      # possible class labels (C=4) 
classidx    = {classlabels[i]:i for i in range(len(classlabels))}     # dict for mapping classlabel to index 
C           = len(classlabels)        # number of classes (Note: K is now the number of nearest-neighbors!!!!!!)
T_txt = forestdata.values[:,0]        # array of class labels of data vectors (class label is first data attribute)
X = forestdata.values[:,1:]           # array of feature vectors (features are remaining attributes)
T = [classidx[t.strip()] for t in T_txt]          # transform text labels 's','h','d','o' to numeric lables 0,1,2,3
N,D=X.shape                           # size and dimensionality of data set
print("Data set 'ForestData' has size N=", N, " and dimensionality D=",D, " and C=", C, " different classes")
print("X[0..9]=\n",X[0:10])
print("T_txt[0..9]=\n",T_txt[0:10])
print("T[0..9]=\n",T[0:10])


Data set 'ForestData' has size N= 523  and dimensionality D= 27  and C= 4  different classes
X[0..9]=
 [[39 36 57 91 59 101 93 27 60 75.7 14.86 40.35 7.97 -32.92 -38.92 -14.94
  4.47 -2.36 -18.41 -1.88 -6.43 -21.03 -1.6 -6.18 -22.5 -5.2 -7.86]
 [84 30 57 112 51 98 92 26 62 30.58 20.42 39.83 -16.74 -24.92 -36.33 -15.67
  8.16 -2.26 -16.27 -1.95 -6.25 -18.79 -1.99 -6.18 -23.41 -8.87 -10.83]
 [53 25 49 99 51 93 84 26 58 63.2 26.7 49.28 3.25 -24.89 -30.38 -3.6 4.15
  -1.46 -15.92 -1.79 -4.64 -17.73 -0.48 -4.69 -19.97 -4.1 -7.07]
 [59 26 49 103 47 92 82 25 56 55.54 24.5 47.9 -6.2 -20.98 -30.28 -5.03 7.77
  2.68 -13.77 -2.53 -6.34 -22.03 -2.34 -6.6 -27.1 -7.99 -10.81]
 [57 49 66 103 64 106 114 28 59 59.44 2.62 32.02 -1.33 -37.99 -43.57 -34.25
  1.83 -2.94 -21.74 -1.64 -4.62 -23.74 -0.85 -5.5 -22.83 -2.74 -5.84]
 [85 28 56 120 52 98 101 27 65 35.14 23.43 42.29 -16.58 -25.43 -34.14
  -17.45 1.58 -10.28 -26.18 -1.89 -5.89 -34.92 -1.89 -8.05 -29.72 -1.94
  -4.94]
 [56 29 50 93 51 94 77 26 58 62.

# b)

In [3]:
# (II) Test KNN-classifier with S-fold cross validation
S_list=[5]                            # parameter S for cross validation; INSERT appropriate values
K_list=[3]                            # number K of nearest neighbors; INSERT appropriate values
accuracy = np.zeros((len(S_list),len(K_list)));   # array to save accuracy of classifier for each value of S and K
for i in range(len(S_list)):
    S=S_list[i]                      # do an S-fold cross validation
    for j in range(len(K_list)):
        K=K_list[j]
        t1=clock()                   # start time
        knnc = FastKNNClassifier(4,K)            # REPLACE! create appropriate KNN classifier (with kd-trees) 
        pE,pCE = knnc.crossvalidate(S,X,T)      # REPLACE! Do S-fold cross validation and get error probabilities / confusion matrix
        t2=clock()                            # end time
        time_comp=t2-t1                       # computing time in seconds
        print( "\nS=",S," fold cross validation using the",K,"-NNClassifier with KD-Trees yields the following results:")
        print( "Classification error probability = ", pE)
        print( "Accuracy = ", 1.0-pE)
        print( "Confusion Error Probabilities p(class i|class j) = \n", pCE)
        print( "Computing time = ", time_comp, " sec")
        accuracy[i,j]=1.0-pE
print( "\naccuracy=\n",accuracy)
print( "\np_classerror=\n",1.0-accuracy)



S= 5  fold cross validation using the 3 -NNClassifier with KD-Trees yields the following results:
Classification error probability =  0.1089866156787763
Accuracy =  0.8910133843212237
Confusion Error Probabilities p(class i|class j) = 
 [[ 0.93333333  0.11627907  0.04402516  0.03614458]
 [ 0.05641026  0.88372093  0.00628931  0.        ]
 [ 0.01025641  0.          0.90566038  0.19277108]
 [ 0.          0.          0.04402516  0.77108434]]
Computing time =  2.2497830000000003  sec

accuracy=
 [[ 0.89101338]]

p_classerror=
 [[ 0.10898662]]


# c)

- die kleinsten S und k scheinen die beste Accuracy zu geben

In [4]:
# (II) Test KNN-classifier with S-fold cross validation
S_list=[1, 2, 3, 5, 10, 100]                            # parameter S for cross validation; INSERT appropriate values
K_list=[1,2,3,4,5,10,15,20]                            # number K of nearest neighbors; INSERT appropriate values
accuracy = np.zeros((len(S_list),len(K_list)));   # array to save accuracy of classifier for each value of S and K
for i in range(len(S_list)):
    S=S_list[i]                      # do an S-fold cross validation
    for j in range(len(K_list)):
        K=K_list[j]
        t1=clock()                   # start time
        knnc = FastKNNClassifier(4,K)            # REPLACE! create appropriate KNN classifier (with kd-trees) 
        pE,pCE = knnc.crossvalidate(S,X,T)      # REPLACE! Do S-fold cross validation and get error probabilities / confusion matrix
        t2=clock()                            # end time
        time_comp=t2-t1                       # computing time in seconds
        print( "\nS=",S," fold cross validation using the",K,"-NNClassifier with KD-Trees yields the following results:")
        print( "Classification error probability = ", pE)
        print( "Accuracy = ", 1.0-pE)
        print( "Confusion Error Probabilities p(class i|class j) = \n", pCE)
        print( "Computing time = ", time_comp, " sec")
        accuracy[i,j]=1.0-pE
print( "\naccuracy=\n",accuracy)
print( "\np_classerror=\n",1.0-accuracy)


S= 1  fold cross validation using the 1 -NNClassifier with KD-Trees yields the following results:
Classification error probability =  0.0
Accuracy =  1.0
Confusion Error Probabilities p(class i|class j) = 
 [[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]
Computing time =  0.28185199999999977  sec

S= 1  fold cross validation using the 2 -NNClassifier with KD-Trees yields the following results:
Classification error probability =  0.06883365200764818
Accuracy =  0.9311663479923518
Confusion Error Probabilities p(class i|class j) = 
 [[ 1.          0.10465116  0.05660377  0.02409639]
 [ 0.          0.89534884  0.01257862  0.        ]
 [ 0.          0.          0.93081761  0.1686747 ]
 [ 0.          0.          0.          0.80722892]]
Computing time =  2.018591  sec

S= 1  fold cross validation using the 3 -NNClassifier with KD-Trees yields the following results:
Classification error probability =  0.06692160611854685
Accuracy =  0.9330783938814532
Confusion 


S= 3  fold cross validation using the 3 -NNClassifier with KD-Trees yields the following results:
Classification error probability =  0.12619502868068833
Accuracy =  0.8738049713193117
Confusion Error Probabilities p(class i|class j) = 
 [[ 0.91794872  0.11627907  0.08176101  0.03614458]
 [ 0.06153846  0.88372093  0.00628931  0.        ]
 [ 0.01538462  0.          0.86792453  0.19277108]
 [ 0.00512821  0.          0.04402516  0.77108434]]
Computing time =  1.9989929999999987  sec

S= 3  fold cross validation using the 4 -NNClassifier with KD-Trees yields the following results:
Classification error probability =  0.13001912045889102
Accuracy =  0.869980879541109
Confusion Error Probabilities p(class i|class j) = 
 [[ 0.94871795  0.20930233  0.08176101  0.02409639]
 [ 0.03589744  0.79069767  0.          0.        ]
 [ 0.01538462  0.          0.88679245  0.24096386]
 [ 0.          0.          0.03144654  0.73493976]]
Computing time =  2.052990000000001  sec

S= 3  fold cross validation u


S= 10  fold cross validation using the 4 -NNClassifier with KD-Trees yields the following results:
Classification error probability =  0.11854684512428298
Accuracy =  0.881453154875717
Confusion Error Probabilities p(class i|class j) = 
 [[ 0.94871795  0.1627907   0.0754717   0.02409639]
 [ 0.03589744  0.8372093   0.          0.        ]
 [ 0.01538462  0.          0.89937107  0.24096386]
 [ 0.          0.          0.02515723  0.73493976]]
Computing time =  2.6154590000000013  sec

S= 10  fold cross validation using the 5 -NNClassifier with KD-Trees yields the following results:
Classification error probability =  0.1089866156787763
Accuracy =  0.8910133843212237
Confusion Error Probabilities p(class i|class j) = 
 [[ 0.93333333  0.12790698  0.04402516  0.02409639]
 [ 0.05128205  0.87209302  0.00628931  0.        ]
 [ 0.01538462  0.          0.90566038  0.19277108]
 [ 0.          0.          0.04402516  0.78313253]]
Computing time =  2.7350299999999947  sec

S= 10  fold cross validatio

# d)

Man könnte die Trainingsdaten als implizierte Parameter verstehen, auch die Art wie ein kd-Tree gebildet wird (Median oder Mittelwert ?) ist eine Art Parameter